name: Build Android APK From Scratch

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # هذه الخطوة ستقوم بتحميل وتثبيت Gradle يدوياً لأن الملف مفقود عندك
      - name: Install Gradle
        run: |
          sudo apt-get install gradle -y
          gradle wrapper

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Finished-App
          path: "**/build/outputs/apk/debug/*.apk"
